version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - crm-network
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: crm_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge

volumes:
  postgres-data:
